settings:
  sync_interval: 3600  # Đồng bộ mỗi 1 giờ (giây)
  max_retries: 3
  timeout: 30
  data_retention_days: 30

devices:
  - name: "Main Entrance"
    ip: "192.168.1.201"
    port: 4370
    device_id: "MCC001"
    enabled: true
    username: ""  # Nếu có authentication
    password: ""  # Nếu có authentication
  - name: "Back Door" 
    ip: "192.168.1.202"
    port: 4370
    device_id: "MCC002"
    enabled: true
    username: ""  # Nếu có authentication
    password: ""  # Nếu có authentication 